const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function fetchTeslaPrice() {
  try {
    const url = "https://query1.finance.yahoo.com/v8/finance/chart/TSLA?interval=1d&range=1d";
    const res = await fetch(url, {
      headers: { "User-Agent": "Mozilla/5.0" },
    });
    const data = await res.json();
    const price = data.chart?.result?.[0]?.meta?.regularMarketPrice;
    if (price && price > 0) return price;
  } catch (err) {
    console.warn("⚠ Could not fetch live TSLA price, using fallback");
  }
  return 350.0;
}

async function main() {
  console.log("🚀 Starting deployment to:", hre.network.name);

  const teslaPrice = await fetchTeslaPrice();
  const oraclePrice = BigInt(Math.round(teslaPrice * 1e8));
  console.log(`📈 TSLA price: $${teslaPrice.toFixed(2)} (oracle: ${oraclePrice})`);

  // Use chain timestamp to prevent underflow
  const block = await hre.ethers.provider.getBlock("latest");
  const now = block ? block.timestamp : Math.floor(Date.now() / 1000) - 60;
  console.log(`🕒 Chain timestamp: ${now}`);

  // Deploy MockUSDC
  const MockUSDC = await hre.ethers.getContractFactory("MockUSDC");
  const usdc = await MockUSDC.deploy();
  await usdc.waitForDeployment();
  const usdcAddress = await usdc.getAddress();
  console.log("✅ MockUSDC:", usdcAddress);

  // Deploy MockChainlinkOracle
  const MockOracle = await hre.ethers.getContractFactory("MockChainlinkOracle");
  const oracle = await MockOracle.deploy(oraclePrice, now);
  await oracle.waitForDeployment();
  const oracleAddress = await oracle.getAddress();
  console.log("✅ MockOracle:", oracleAddress);

  // Deploy HoodGap
  const HoodGap = await hre.ethers.getContractFactory("HoodGap");
  const hoodgap = await HoodGap.deploy(usdcAddress, oracleAddress);
  await hoodgap.waitForDeployment();
  const hoodgapAddress = await hoodgap.getAddress();
  console.log("✅ HoodGap:", hoodgapAddress);

  // Auto-write frontend/.env.local
  const envContent = [
    "# HoodGap Frontend Environment — auto-generated by deploy.js",
    `# Deployed to ${hre.network.name} at ${new Date().toISOString()}`,
    `NEXT_PUBLIC_HOODGAP_ADDRESS=${hoodgapAddress}`,
    `NEXT_PUBLIC_USDC_ADDRESS=${usdcAddress}`,
    `NEXT_PUBLIC_ORACLE_ADDRESS=${oracleAddress}`,
    "NEXT_PUBLIC_RPC_URL=https://rpc.testnet.chain.robinhood.com",
    "NEXT_PUBLIC_CHAIN_ID=46630",
    "",
  ].join("\n");

  const envPath = path.join(__dirname, "..", "frontend", ".env.local");
  fs.writeFileSync(envPath, envContent, "utf8");
  console.log("\n✅ Auto-wrote frontend/.env.local");

  console.log("\n📋 Summary:");
  console.log("   USDC:    ", usdcAddress);
  console.log("   Oracle:  ", oracleAddress);
  console.log("   HoodGap: ", hoodgapAddress);
  console.log("\n🎯 Next: restart `npm run dev` in frontend/");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});