/**
 * verify.js — Verify deployed contracts on block explorer
 *
 * Reads addresses from frontend/.env.local (auto-generated by deploy.js)
 * and submits source code verification to the Robinhood Chain explorer.
 *
 * Usage:
 *   npx hardhat run scripts/verify.js --network robinhoodTestnet
 */

const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function getDeployedAddresses() {
  const envPath = path.join(__dirname, "..", "frontend", ".env.local");
  if (!fs.existsSync(envPath)) {
    throw new Error("frontend/.env.local not found. Run deploy.js first.");
  }

  const env = fs.readFileSync(envPath, "utf8");
  const match = (key) => {
    const m = env.match(new RegExp(`${key}=(.+)`));
    return m ? m[1].trim() : null;
  };

  const hoodgap = match("NEXT_PUBLIC_HOODGAP_ADDRESS");
  const usdc = match("NEXT_PUBLIC_USDC_ADDRESS");
  const oracle = match("NEXT_PUBLIC_ORACLE_ADDRESS");

  if (!hoodgap || !usdc || !oracle) {
    throw new Error("Missing contract addresses in frontend/.env.local");
  }

  return { hoodgap, usdc, oracle };
}

async function verifyContract(name, address, constructorArgs) {
  console.log(`\n  Verifying ${name} at ${address}...`);
  try {
    await hre.run("verify:verify", {
      address,
      constructorArguments: constructorArgs,
    });
    console.log(`  ✅ ${name} verified!`);
    return true;
  } catch (err) {
    if (err.message.includes("Already Verified") || err.message.includes("already verified")) {
      console.log(`  ⚠️  ${name} already verified`);
      return true;
    }
    console.error(`  ❌ ${name} verification failed:`, err.message);
    return false;
  }
}

async function main() {
  console.log("\n🔍 HoodGap — Contract Verification");
  console.log("   Network:", hre.network.name);
  console.log("─".repeat(50));

  if (hre.network.name === "localhost" || hre.network.name === "hardhat") {
    console.log("\n  ⚠️  Skipping verification on local network");
    return;
  }

  const { hoodgap, usdc, oracle } = await getDeployedAddresses();
  console.log("   HoodGap:", hoodgap);
  console.log("   USDC:   ", usdc);
  console.log("   Oracle: ", oracle);
  console.log("─".repeat(50));

  let success = 0;
  let total = 0;

  // MockUSDC: no constructor args
  total++;
  if (await verifyContract("MockUSDC", usdc, [])) success++;

  // MockChainlinkOracle: constructor(int256 _price, uint256 _updatedAt)
  // We need to reconstruct the args — read from oracle contract
  try {
    const oracleContract = await hre.ethers.getContractAt("MockChainlinkOracle", oracle);
    const price = await oracleContract.price();
    const updatedAt = await oracleContract.updatedAt();
    total++;
    if (await verifyContract("MockChainlinkOracle", oracle, [price, updatedAt])) success++;
  } catch (err) {
    console.log(`\n  ⚠️  Could not read oracle state for verification: ${err.message}`);
    console.log("     Try verifying MockChainlinkOracle manually on the explorer.");
    total++;
  }

  // HoodGap: constructor(address _usdc, address _oracle)
  total++;
  if (await verifyContract("HoodGap", hoodgap, [usdc, oracle])) success++;

  // Summary
  console.log("\n─".repeat(50));
  console.log(`\n  📋 Results: ${success}/${total} contracts verified`);

  if (success === total) {
    console.log("  🎉 All contracts verified successfully!\n");
  } else {
    console.log("  ⚠️  Some verifications failed — check errors above.\n");
    console.log("  Manual verification:");
    console.log(`    https://explorer.testnet.chain.robinhood.com/address/${hoodgap}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
